# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726528ec4f6a77aeb8a4a381ee2cf10d18775f4f27ec15202306e193929f464043762ab92f6f003b88318d71e931efd76c686eccd0c479abcb291858a519ee2f

test:
  secret_key_base: e49733d7eac49e401c4d0ef7194ee49c5c0f644e2e7da2bdf89827259a374c0a0b34328574b50ca27081c0c3e1f1352231ea03b9ea9599b5a8224e216638a887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
